name: 'Sphinx Deploy to GH-Pages'
description: 'Builds and deploys a Sphinx site to the gh-pages branch'

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.9'

runs:
  using: 'composite'
  steps:
    - name: actions/setup-python@v4
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip
      shell: bash

    - name: Install Sphinx and tools
      run: |
        pip install -U sphinx myst-parser
        pip install -U sphinx_rtd_theme
      shell: bash

    - name: Install PHOTON tools
      run: |
        pip install -U git+https://github.com/photon-platform/photon-ablog.git
        pip install -U git+https://github.com/photon-platform/photon-sphinx-theme.git
      shell: bash

    - name: Build Sphinx
      run: |
        cd docsrc
        ablog clean
        ablog build
        cp CNAME ../docs/CNAME
        cd ..
      shell: bash

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./docs
        publish_branch: gh-pages
      # shell: bash
