name: 'Sphinx Deploy to GH-Pages'
description: 'Builds and deploys a Sphinx site to the gh-pages branch'

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.10'
  modules_repo_urls:
    description: 'GitHub URLs of the current modules to be pip installed'
    required: false


runs:
  using: 'composite'
  steps:
    - name: actions/setup-python@v4
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Upgrade Pip
      run: |
        echo 
        echo UPGRADE PIP ==========================
        python -m pip install --upgrade pip
      shell: bash

    - name: Install Graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz
      shell: bash

    - name: Install modules
      run: |
        echo
        echo
        echo INSTALL pre modules ==========================================
        IFS=',' read -ra ADDR <<< "${{ inputs.modules_repo_urls }}"
        for url in "${ADDR[@]}"; do
          echo " - " $url
          pip install -U git+"$url"
        done
      shell: bash

    - name: Install PHOTON tools
      run: |
        echo
        echo
        echo INSTALL Photon publish  =======================================
        pip install -U git+https://github.com/photon-platform/publish.git
      shell: bash

    - name: Build Sphinx
      run: |
        echo
        echo
        echo Build Sphinx ================================================
        cd docsrc
        # publish clean
        publish build
        # Check if CNAME exists before copying
        if [ -f CNAME ]; then
          cp CNAME ../docs/CNAME
        else
          echo "No CNAME file found; skipping copy step."
        fi
        cd ..
      shell: bash

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./docs
        publish_branch: gh-pages
      # shell: bash
